# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gcloud', '-f', 'gcloud/Dockerfile', '.']
- name: 'gcr.io/$PROJECT_ID/gcloud'
  args: ['info']

images: ['gcr.io/$PROJECT_ID/gcloud']
